spring:
  application.name: bananawhatsapp
#  sql.init.mode: always
  devtools.restart.enabled: true
  datasource:
    ## h2 >>
    url: "jdbc:h2:mem:bananawhatsappdb"
    driverClassName: org.h2.Driver
    username: sa
    password: password
    ## mysql >>
    # url: "jdbc:mysql://localhost:3306/bananawhatsappdb"
    # driverClassName: com.mysql.cj.jdbc.Driver
    # username: root
    # password: root
  jpa:
    show-sql: false
    ## h2 >>
    database-platform: org.hibernate.dialect.H2Dialect
    ## mysql >>
    # database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      generate-ddl: true
    # defer-datasource-initialization: true
## h2 >>
  h2.console:
    enabled: true
    path: /h2-ui


server:
  port: 9090
---

---