spring:
  application.name: MyPersonalBankAPI
#  sql.init.mode: always
  devtools.restart.enabled: true
  datasource:
    #    url: "jdbc:h2:mem:personalapidb"
    url: "jdbc:mysql://localhost:3306/personalapi_db"
    #    driverClassName: org.h2.Driver
    driverClassName: com.mysql.cj.jdbc.Driver
    #    username: sa
    #    password: password
    username: root
    password: root
  jpa:
    show-sql: false
    #    database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      generate-ddl: true
#    defer-datasource-initialization: true
#  h2:
#    console.enabled: true
#    console.path: /h2-ui


server:
  port: 9090
---

---