spring:
  application.name: MyPersonalBankAPI
  sql.init.mode: always
  devtools.restart.enabled: true
  application:
    name: ProductsService
  datasource:
    url: "jdbc:h2:mem:personalapidb"
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      generate-ddl: true
    defer-datasource-initialization: true
  h2:
    console.enabled: true
    console.path: /h2-ui

server:
  port: 9090
---

---